-- Run this in Supabase Dashboard -> SQL Editor

create table if not exists public.portfolio_comments (
  id bigint generated by default as identity primary key,
  user_name text not null,
  content text not null,
  profile_image text,
  is_pinned boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.portfolio_comments enable row level security;

create policy "Anyone can read comments"
  on public.portfolio_comments
  for select
  using (true);

create policy "Anyone can post comments"
  on public.portfolio_comments
  for insert
  with check (true);

create policy "Authenticated users can update comments"
  on public.portfolio_comments
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete comments"
  on public.portfolio_comments
  for delete
  to authenticated
  using (true);

insert into storage.buckets (id, name, public)
values ('profile-images', 'profile-images', true)
on conflict (id) do nothing;

create policy "Public read profile images"
  on storage.objects
  for select
  using (bucket_id = 'profile-images');

create policy "Anyone can upload profile images"
  on storage.objects
  for insert
  with check (bucket_id = 'profile-images');
